name: CI/CD for Gordian API

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_and_deploy:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          make

      - name: Deploy API for Testing
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          BASE: ${{ secrets.BASE }}
          COLLECTION: ${{ secrets.COLLECTION }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
        run: uvicorn Gordian:app --host 0.0.0.0 --port $PORT &

      - name: Test API Deployment
        run: |
          API_URL="http://0.0.0.0:${{ secrets.PORT }}/status"
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" $API_URL)
          if [ $STATUS_CODE -eq 200 ]; then
            echo "API is deployed and responding with status code 200 (OK)"
          else
            echo "Error: API deployment failed. Received status code: $STATUS_CODE"
            exit 1
          fi
          - name: Deploy to Render.com
          env:
            RENDER_WEBHOOK_URL: ${{ secrets.RENDER_WEBHOOK_URL }}
          run: |
            curl -X POST -H "Content-Type: application/json" -d '{"branch": "master"}' $RENDER_WEBHOOK_URL